spring:
  datasource:
    url: jdbc:h2:mem:customers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
server:
  port: 8081